\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={SQL-NoSQL analysis},
            pdfauthor={Kathleen DeBrota},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{SQL-NoSQL analysis}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Kathleen DeBrota}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{April 24, 2019}


\begin{document}
\maketitle

This document is for some analysis and visualizations of the credit card
data set for SQL/NoSQL final project.

Guiding questions: What kind of person is most likely to default on
their credit card payments? What demographic factor(s) are most
important in predicting this?

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(readxl)}
\KeywordTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'dplyr'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     filter, lag
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(lattice)}
\KeywordTok{library}\NormalTok{(rcompanion)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'rcompanion' was built under R version 3.5.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ggplot2)}
\KeywordTok{library}\NormalTok{(Rcmdr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'Rcmdr' was built under R version 3.5.3
\end{verbatim}

\begin{verbatim}
## Loading required package: splines
\end{verbatim}

\begin{verbatim}
## Loading required package: RcmdrMisc
\end{verbatim}

\begin{verbatim}
## Warning: package 'RcmdrMisc' was built under R version 3.5.3
\end{verbatim}

\begin{verbatim}
## Loading required package: car
\end{verbatim}

\begin{verbatim}
## Warning: package 'car' was built under R version 3.5.3
\end{verbatim}

\begin{verbatim}
## Loading required package: carData
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'car'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:dplyr':
## 
##     recode
\end{verbatim}

\begin{verbatim}
## Loading required package: sandwich
\end{verbatim}

\begin{verbatim}
## Warning: package 'sandwich' was built under R version 3.5.3
\end{verbatim}

\begin{verbatim}
## Loading required package: effects
\end{verbatim}

\begin{verbatim}
## Warning: package 'effects' was built under R version 3.5.3
\end{verbatim}

\begin{verbatim}
## Use the command
##     lattice::trellis.par.set(effectsTheme())
##   to customize lattice options for effects plots.
## See ?effectsTheme for details.
\end{verbatim}

\begin{verbatim}
## The Commander GUI is launched only in interactive sessions
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'Rcmdr'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:car':
## 
##     Confint
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(gplots)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'gplots' was built under R version 3.5.3
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'gplots'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:stats':
## 
##     lowess
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(corrplot)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## corrplot 0.84 loaded
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(factoextra)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'factoextra' was built under R version 3.5.3
\end{verbatim}

\begin{verbatim}
## Welcome! Related Books: `Practical Guide To Cluster Analysis in R` at https://goo.gl/13EFCZ
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(rgl)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'rgl' was built under R version 3.5.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(purrr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'purrr'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:car':
## 
##     some
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{setwd}\NormalTok{(}\StringTok{"C:/Users/kdebr/Documents/GitHub/sql-nosql"}\NormalTok{)}
\NormalTok{credit<-}\KeywordTok{read.csv}\NormalTok{(}\DataTypeTok{file=}\StringTok{'cleanData.csv'}\NormalTok{)}
\KeywordTok{head}\NormalTok{(credit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   ID LIMIT_BAL    SEX      EDUCATION MARRIAGE AGE PAY_1 PAY_2 PAY_3 PAY_4
## 1  1     20000 female under graduate  married  24     2     2    -1    -1
## 2  2    120000 female under graduate   single  26    -1     2     0     0
## 3  3     90000 female under graduate   single  34     0     0     0     0
## 4  4     50000 female under graduate  married  37     0     0     0     0
## 5  5     50000   male under graduate  married  57    -1     0    -1     0
## 6  6     50000   male       graduate   single  37     0     0     0     0
##   PAY_5 PAY_6 BILL_AMT1 BILL_AMT2 BILL_AMT3 BILL_AMT4 BILL_AMT5 BILL_AMT6
## 1    -2    -2      3913      3102       689         0         0         0
## 2     0     2      2682      1725      2682      3272      3455      3261
## 3     0     0     29239     14027     13559     14331     14948     15549
## 4     0     0     46990     48233     49291     28314     28959     29547
## 5     0     0      8617      5670     35835     20940     19146     19131
## 6     0     0     64400     57069     57608     19394     19619     20024
##   PAY_AMT1 PAY_AMT2 PAY_AMT3 PAY_AMT4 PAY_AMT5 PAY_AMT6
## 1        0      689        0        0        0        0
## 2        0     1000     1000     1000        0     2000
## 3     1518     1500     1000     1000     1000     5000
## 4     2000     2019     1200     1100     1069     1000
## 5     2000    36681    10000     9000      689      679
## 6     2500     1815      657     1000     1000      800
##   DEFAULT_PAYMENT_NEXT_MONTH
## 1                          1
## 2                          1
## 3                          0
## 4                          0
## 5                          0
## 6                          0
\end{verbatim}

Exploratory views of the data.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(credit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        ID          LIMIT_BAL           SEX                 EDUCATION    
##  Min.   :    1   Min.   :  10000   female:18112   graduate      :10585  
##  1st Qu.: 7501   1st Qu.:  50000   male  :11888   high school   : 4917  
##  Median :15000   Median : 140000                  others        :  123  
##  Mean   :15000   Mean   : 167484                  under graduate:14030  
##  3rd Qu.:22500   3rd Qu.: 240000                  uneducated    :   14  
##  Max.   :30000   Max.   :1000000                  unknown       :  331  
##     MARRIAGE          AGE            PAY_1             PAY_2        
##  married:13659   Min.   :21.00   Min.   :-2.0000   Min.   :-2.0000  
##  others :  323   1st Qu.:28.00   1st Qu.:-1.0000   1st Qu.:-1.0000  
##  single :15964   Median :34.00   Median : 0.0000   Median : 0.0000  
##  unknown:   54   Mean   :35.49   Mean   :-0.0167   Mean   :-0.1338  
##                  3rd Qu.:41.00   3rd Qu.: 0.0000   3rd Qu.: 0.0000  
##                  Max.   :79.00   Max.   : 8.0000   Max.   : 8.0000  
##      PAY_3             PAY_4             PAY_5             PAY_6        
##  Min.   :-2.0000   Min.   :-2.0000   Min.   :-2.0000   Min.   :-2.0000  
##  1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000  
##  Median : 0.0000   Median : 0.0000   Median : 0.0000   Median : 0.0000  
##  Mean   :-0.1662   Mean   :-0.2207   Mean   :-0.2662   Mean   :-0.2911  
##  3rd Qu.: 0.0000   3rd Qu.: 0.0000   3rd Qu.: 0.0000   3rd Qu.: 0.0000  
##  Max.   : 8.0000   Max.   : 8.0000   Max.   : 8.0000   Max.   : 8.0000  
##    BILL_AMT1         BILL_AMT2        BILL_AMT3         BILL_AMT4      
##  Min.   :-165580   Min.   :-69777   Min.   :-157264   Min.   :-170000  
##  1st Qu.:   3559   1st Qu.:  2985   1st Qu.:   2666   1st Qu.:   2327  
##  Median :  22382   Median : 21200   Median :  20089   Median :  19052  
##  Mean   :  51223   Mean   : 49179   Mean   :  47013   Mean   :  43263  
##  3rd Qu.:  67091   3rd Qu.: 64006   3rd Qu.:  60165   3rd Qu.:  54506  
##  Max.   : 964511   Max.   :983931   Max.   :1664089   Max.   : 891586  
##    BILL_AMT5        BILL_AMT6          PAY_AMT1         PAY_AMT2      
##  Min.   :-81334   Min.   :-339603   Min.   :     0   Min.   :      0  
##  1st Qu.:  1763   1st Qu.:   1256   1st Qu.:  1000   1st Qu.:    833  
##  Median : 18105   Median :  17071   Median :  2100   Median :   2009  
##  Mean   : 40311   Mean   :  38872   Mean   :  5664   Mean   :   5921  
##  3rd Qu.: 50191   3rd Qu.:  49198   3rd Qu.:  5006   3rd Qu.:   5000  
##  Max.   :927171   Max.   : 961664   Max.   :873552   Max.   :1684259  
##     PAY_AMT3         PAY_AMT4         PAY_AMT5           PAY_AMT6       
##  Min.   :     0   Min.   :     0   Min.   :     0.0   Min.   :     0.0  
##  1st Qu.:   390   1st Qu.:   296   1st Qu.:   252.5   1st Qu.:   117.8  
##  Median :  1800   Median :  1500   Median :  1500.0   Median :  1500.0  
##  Mean   :  5226   Mean   :  4826   Mean   :  4799.4   Mean   :  5215.5  
##  3rd Qu.:  4505   3rd Qu.:  4013   3rd Qu.:  4031.5   3rd Qu.:  4000.0  
##  Max.   :896040   Max.   :621000   Max.   :426529.0   Max.   :528666.0  
##  DEFAULT_PAYMENT_NEXT_MONTH
##  Min.   :0.0000            
##  1st Qu.:0.0000            
##  Median :0.0000            
##  Mean   :0.2212            
##  3rd Qu.:0.0000            
##  Max.   :1.0000
\end{verbatim}

More of the respondents were women (18,112 vs 11,888 men). The majority
were undergraduates (14,030) with some graduates (10,585) and fewer who
were high-school educated, uneducated, unknown, or `other'. The majority
were not married: 15,964, but many were married: 13,659. A few were
`other' or unknown for marital status. The mean age of the respondents
was 35.49 years, with the youngest participants at 21 years and oldest
at 79 years.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#view thistograms of demographic data}
\KeywordTok{hist}\NormalTok{(credit}\OperatorTok{$}\NormalTok{AGE, }\DataTypeTok{main=}\StringTok{'Histogram of age distribution of respondents'}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{'Frequency'}\NormalTok{, }\DataTypeTok{xlab=}\StringTok{'Age in years'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-4-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Boxplot of the payment status for each of the 6 payments.}
\KeywordTok{boxplot}\NormalTok{(credit}\OperatorTok{$}\NormalTok{PAY_}\DecValTok{1}\NormalTok{, credit}\OperatorTok{$}\NormalTok{PAY_}\DecValTok{2}\NormalTok{, credit}\OperatorTok{$}\NormalTok{PAY_}\DecValTok{3}\NormalTok{, credit}\OperatorTok{$}\NormalTok{PAY_}\DecValTok{4}\NormalTok{, credit}\OperatorTok{$}\NormalTok{PAY_}\DecValTok{5}\NormalTok{, credit}\OperatorTok{$}\NormalTok{PAY_}\DecValTok{6}\NormalTok{, }\DataTypeTok{main=}\StringTok{'Payment status of each of 6 payments'}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{'Status code'}\NormalTok{, }\DataTypeTok{xlab=}\StringTok{'Payment number'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-4-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Boxplot of payment amount for each of 6 payments.}
\KeywordTok{boxplot}\NormalTok{(credit}\OperatorTok{$}\NormalTok{BILL_AMT1, credit}\OperatorTok{$}\NormalTok{BILL_AMT2, credit}\OperatorTok{$}\NormalTok{BILL_AMT3, credit}\OperatorTok{$}\NormalTok{BILL_AMT4, credit}\OperatorTok{$}\NormalTok{BILL_AMT5, credit}\OperatorTok{$}\NormalTok{BILL_AMT6, }\DataTypeTok{main=}\StringTok{'Bill amount of each of 6 payments'}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{'Bill amount (NT dollars)'}\NormalTok{, }\DataTypeTok{xlab=}\StringTok{'Payment number'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-4-3.pdf}
Separate out just those who defaulted and who did not. Visualize general
demographic differences

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{will_default<-}\KeywordTok{subset}\NormalTok{(credit, DEFAULT_PAYMENT_NEXT_MONTH}\OperatorTok{==}\DecValTok{1}\NormalTok{)}
\NormalTok{z3countdef<-}\KeywordTok{table}\NormalTok{(will_default}\OperatorTok{$}\NormalTok{AGE, will_default}\OperatorTok{$}\NormalTok{MARRIAGE)}

\NormalTok{will_pay<-}\KeywordTok{subset}\NormalTok{(credit, DEFAULT_PAYMENT_NEXT_MONTH}\OperatorTok{==}\DecValTok{0}\NormalTok{)}
\CommentTok{#countpay<- table(will_pay$AGE, will_pay$MARRIAGE)}

\NormalTok{credit}\OperatorTok{$}\NormalTok{MARRIAGE<-}\KeywordTok{as.factor}\NormalTok{(credit}\OperatorTok{$}\NormalTok{MARRIAGE)}
\NormalTok{credit}\OperatorTok{$}\NormalTok{DEFAULT_PAYMENT_NEXT_MONTH <-}\KeywordTok{as.factor}\NormalTok{(credit}\OperatorTok{$}\NormalTok{DEFAULT_PAYMENT_NEXT_MONTH)}

\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow=}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\CommentTok{#View ages of those who did and did not default.}
\KeywordTok{hist}\NormalTok{(will_default}\OperatorTok{$}\NormalTok{AGE, }\DataTypeTok{main=}\StringTok{'Age distribution: Will default'}\NormalTok{, }\DataTypeTok{xlab=}\StringTok{'Age (years)'}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{'Frequency'}\NormalTok{)}
\KeywordTok{hist}\NormalTok{(will_pay}\OperatorTok{$}\NormalTok{AGE, }\DataTypeTok{main=}\StringTok{'Age distribution: Will not default'}\NormalTok{, }\DataTypeTok{xlab=}\StringTok{'Age(years)'}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{'Frequency'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#----------------------------------------------}

\CommentTok{#View marital status of those who did/didn't default.}
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow=}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\NormalTok{marriage <-credit }\OperatorTok{%>%}\StringTok{ }\KeywordTok{group_by}\NormalTok{(MARRIAGE, DEFAULT_PAYMENT_NEXT_MONTH) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{count}\NormalTok{(DEFAULT_PAYMENT_NEXT_MONTH)}
\NormalTok{marriage }\CommentTok{#this shows the counts of people per group.}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 8 x 3
## # Groups:   MARRIAGE, DEFAULT_PAYMENT_NEXT_MONTH [8]
##   MARRIAGE DEFAULT_PAYMENT_NEXT_MONTH     n
##   <fct>    <fct>                      <int>
## 1 married  0                          10453
## 2 married  1                           3206
## 3 others   0                            239
## 4 others   1                             84
## 5 single   0                          12623
## 6 single   1                           3341
## 7 unknown  0                             49
## 8 unknown  1                              5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#This is split by payment default status}
\KeywordTok{ggplot}\NormalTok{(marriage, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{fill=}\NormalTok{MARRIAGE, }\DataTypeTok{x=}\NormalTok{DEFAULT_PAYMENT_NEXT_MONTH, }\DataTypeTok{y=}\NormalTok{n))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'identity'}\NormalTok{, }\DataTypeTok{position=}\StringTok{'fill'}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Default payment status by marital status"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Fraction of total"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{'Default payment status'}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{fill=}\StringTok{'Marital status'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-5-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#This is split by marriage status}
\KeywordTok{ggplot}\NormalTok{(marriage, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{fill=}\NormalTok{DEFAULT_PAYMENT_NEXT_MONTH, }\DataTypeTok{x=}\NormalTok{MARRIAGE, }\DataTypeTok{y=}\NormalTok{n))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'identity'}\NormalTok{, }\DataTypeTok{position=}\StringTok{'fill'}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Default payment status by marital status"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Fraction of total"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{'Marital status'}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{fill=}\StringTok{'Default payment }\CharTok{\textbackslash{}n}\StringTok{status'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-5-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#barchart(marriage$n~marriage$DEFAULT_PAYMENT_NEXT_MONTH, ylab='Number of people', xlab='Payment default status', main='Influence of marital status on default payments', stacked=TRUE, groups=marriage$MARRIAGE, auto.key=list(space='right', title='Marriage status', cex.title=0.8))}

\CommentTok{#----------------------------------------------}

\CommentTok{#View education status of those who did/did not default.}
\NormalTok{education <-credit }\OperatorTok{%>%}\StringTok{ }\KeywordTok{group_by}\NormalTok{(EDUCATION, DEFAULT_PAYMENT_NEXT_MONTH) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{count}\NormalTok{(DEFAULT_PAYMENT_NEXT_MONTH)}
\NormalTok{education }\CommentTok{#this shows the counts of people per group.}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 11 x 3
## # Groups:   EDUCATION, DEFAULT_PAYMENT_NEXT_MONTH [11]
##    EDUCATION      DEFAULT_PAYMENT_NEXT_MONTH     n
##    <fct>          <fct>                      <int>
##  1 graduate       0                           8549
##  2 graduate       1                           2036
##  3 high school    0                           3680
##  4 high school    1                           1237
##  5 others         0                            116
##  6 others         1                              7
##  7 under graduate 0                          10700
##  8 under graduate 1                           3330
##  9 uneducated     0                             14
## 10 unknown        0                            305
## 11 unknown        1                             26
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#This is split by education status}
\KeywordTok{ggplot}\NormalTok{(education, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{fill=}\NormalTok{DEFAULT_PAYMENT_NEXT_MONTH, }\DataTypeTok{x=}\NormalTok{EDUCATION, }\DataTypeTok{y=}\NormalTok{n))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'identity'}\NormalTok{, }\DataTypeTok{position=}\StringTok{'fill'}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Default payment status by educational status"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Fraction of total"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{'Educational status'}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{fill=}\StringTok{'Default payment }\CharTok{\textbackslash{}n}\StringTok{status'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-5-4.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#barchart(education$n~education$DEFAULT_PAYMENT_NEXT_MONTH, ylab='Number of people', xlab='Payment default status', main='Influence of educational status on default payments', groups=education$EDUCATION, auto.key=list(space='right', title='Educational status', cex.title=0.8))}


\CommentTok{#What about the link between total bill amount and default status, or total bill amount and how many months they pushed back the payment?}

\CommentTok{#----------------------------------------------}

\CommentTok{#View sex of those who did or did not default}

\NormalTok{sex <-credit }\OperatorTok{%>%}\StringTok{ }\KeywordTok{group_by}\NormalTok{(SEX, DEFAULT_PAYMENT_NEXT_MONTH) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{count}\NormalTok{(DEFAULT_PAYMENT_NEXT_MONTH)}
\NormalTok{sex }\CommentTok{#this shows the counts of people per group.}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 4 x 3
## # Groups:   SEX, DEFAULT_PAYMENT_NEXT_MONTH [4]
##   SEX    DEFAULT_PAYMENT_NEXT_MONTH     n
##   <fct>  <fct>                      <int>
## 1 female 0                          14349
## 2 female 1                           3763
## 3 male   0                           9015
## 4 male   1                           2873
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#This is split by education status}
\KeywordTok{ggplot}\NormalTok{(sex, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{fill=}\NormalTok{DEFAULT_PAYMENT_NEXT_MONTH, }\DataTypeTok{x=}\NormalTok{SEX, }\DataTypeTok{y=}\NormalTok{n))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'identity'}\NormalTok{, }\DataTypeTok{position=}\StringTok{'fill'}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Default payment status by sex"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Fraction of total"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{'Sex'}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{fill=}\StringTok{'Default payment }\CharTok{\textbackslash{}n}\StringTok{status'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-5-5.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#----------------------------------------------}

\CommentTok{#View credit limit of defaulters and not defaulters}

\KeywordTok{bwplot}\NormalTok{(credit}\OperatorTok{$}\NormalTok{LIMIT_BAL}\OperatorTok{~}\NormalTok{credit}\OperatorTok{$}\NormalTok{DEFAULT_PAYMENT_NEXT_MONTH, }\DataTypeTok{xlab=}\StringTok{'Default payment status'}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{'Credit limit, NT dollar'}\NormalTok{, }\DataTypeTok{main=}\StringTok{'Credit limit by default payment status'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-5-6.pdf}
1. Are younger people more or less likely to default on payments?

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Check normalcy of the data}
\KeywordTok{normalityTest}\NormalTok{(AGE }\OperatorTok{~}\StringTok{ }\NormalTok{DEFAULT_PAYMENT_NEXT_MONTH, }\DataTypeTok{test=}\StringTok{"ad.test"}\NormalTok{, }\DataTypeTok{data=}\NormalTok{credit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  --------
##  DEFAULT_PAYMENT_NEXT_MONTH = 0 
## 
##  Anderson-Darling normality test
## 
## data:  AGE
## A = 314.97, p-value < 2.2e-16
## 
##  --------
##  DEFAULT_PAYMENT_NEXT_MONTH = 1 
## 
##  Anderson-Darling normality test
## 
## data:  AGE
## A = 87.389, p-value < 2.2e-16
## 
##  --------
## 
##  p-values adjusted by the Holm method:
##   unadjusted adjusted  
## 0 < 2.22e-16 < 2.22e-16
## 1 < 2.22e-16 < 2.22e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#The data are NOT normally distributed (p<<0.05)}
\CommentTok{#Check heteroscedasticity}
\KeywordTok{with}\NormalTok{(credit, }\KeywordTok{tapply}\NormalTok{(AGE, DEFAULT_PAYMENT_NEXT_MONTH, var, }\DataTypeTok{na.rm=}\OtherTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        0        1 
## 82.39837 93.96275
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{bartlett.test}\NormalTok{(AGE }\OperatorTok{~}\StringTok{ }\NormalTok{DEFAULT_PAYMENT_NEXT_MONTH, }\DataTypeTok{data=}\NormalTok{credit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Bartlett test of homogeneity of variances
## 
## data:  AGE by DEFAULT_PAYMENT_NEXT_MONTH
## Bartlett's K-squared = 45.647, df = 1, p-value = 1.416e-11
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Data are homoscedastic; p<<0.05}

\CommentTok{#Run a non parametric test to check differences of means}
\KeywordTok{with}\NormalTok{(credit, }\KeywordTok{tapply}\NormalTok{(AGE, DEFAULT_PAYMENT_NEXT_MONTH, median, }\DataTypeTok{na.rm=}\OtherTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  0  1 
## 34 34
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{kruskal.test}\NormalTok{(AGE }\OperatorTok{~}\StringTok{ }\NormalTok{DEFAULT_PAYMENT_NEXT_MONTH, }\DataTypeTok{data=}\NormalTok{credit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Kruskal-Wallis rank sum test
## 
## data:  AGE by DEFAULT_PAYMENT_NEXT_MONTH
## Kruskal-Wallis chi-squared = 0.7953, df = 1, p-value = 0.3725
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# #ANOVA to determine difference of mean age in each group (default vs not default)}
\CommentTok{# AnovaModel.1 <- aov(AGE ~ DEFAULT_PAYMENT_NEXT_MONTH, data=credit)}
\CommentTok{# summary(AnovaModel.1)}
\CommentTok{# with(credit, numSummary(AGE, groups=DEFAULT_PAYMENT_NEXT_MONTH, }
\CommentTok{#   statistics=c("mean", "sd")))}
\end{Highlighting}
\end{Shaded}

the Kruskal-Wallis test shows there is NO significant difference in the
mean ages between groups (did and did not default).

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Are higher-educated people more or less likely to default?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Performing pearson Chi-sq test of independence.}
\CommentTok{#Null hypothesis: "education level is independent of whether or not someone will default, at the 0.05 significance level."}

\CommentTok{#First tabulating the contingency table of the two variables}
\NormalTok{educ_conting=}\KeywordTok{table}\NormalTok{(credit}\OperatorTok{$}\NormalTok{EDUCATION, credit}\OperatorTok{$}\NormalTok{DEFAULT_PAYMENT_NEXT_MONTH)}
\NormalTok{educ_conting }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                 
##                      0     1
##   graduate        8549  2036
##   high school     3680  1237
##   others           116     7
##   under graduate 10700  3330
##   uneducated        14     0
##   unknown          305    26
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{balloonplot}\NormalTok{(}\KeywordTok{t}\NormalTok{(educ_conting), }\DataTypeTok{main=}\StringTok{'Education level frequency by default payment status'}\NormalTok{, }\DataTypeTok{xlab=}\StringTok{'Default payment status'}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{'Educational status'}\NormalTok{, }\DataTypeTok{label=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{show.margins=}\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-7-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#This gives the counts of each category in each 'axis' specified}

\CommentTok{#Chi-squared test}
\NormalTok{chi_sq_test<-}\KeywordTok{chisq.test}\NormalTok{(educ_conting)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in chisq.test(educ_conting): Chi-squared approximation may be
## incorrect
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{chi_sq_test}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's Chi-squared test
## 
## data:  educ_conting
## X-squared = 161.07, df = 5, p-value < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#round(chi_sq_test$expected,2)}

\CommentTok{#To determine the nature of the dependence between rows (education) and columns (payment status), use chi-sq residuals (Pearson residuals)}
\NormalTok{chisq_resid<-}\KeywordTok{round}\NormalTok{(chi_sq_test}\OperatorTok{$}\NormalTok{residuals,}\DecValTok{3}\NormalTok{)}
\NormalTok{chisq_resid}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                 
##                       0      1
##   graduate        3.364 -6.312
##   high school    -2.414  4.529
##   others          2.065 -3.874
##   under graduate -2.167  4.067
##   uneducated      0.938 -1.760
##   unknown         2.941 -5.518
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Visualization of the residuals shows the positive (blue) and negative (red) correlations between the row and column variables.}
\KeywordTok{corrplot}\NormalTok{(chisq_resid, }\DataTypeTok{is.cor=}\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-7-2.pdf}
The results of the chi square test show that there is a highly
significant interaction between education level and probability that
someone will default on their credit card bill
(p\textless{}\textless{}\textless{}0.05).

We can also see from the chi-squared test and analysis of the residuals
in the corrplot that there is a strong positive association between
those who defult and those with either a high school or undergraduate
education. Meanwhile, defaulting is negatively associated with having a
graduate education or `uneducated, other, or unknown' education level.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\item
  How is credit limit associated with likelihood to default? How is
  credit limit associated with age and education level?
\item
  At what bill value is someone more likely to default on their payment?
  Are there any demographic trends that emerge there?
\item
  Is the amount of one single bill more influential than whether or not
  the person delayed their last bill in deciding whether someone will
  default?
\item
  How does marital status affect probability of defaulting?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Performing pearson Chi-sq test of independence.}
\CommentTok{#Null hypothesis: "marital status is independent of whether or not someone will default, at the 0.05 significance level."}

\CommentTok{#First tabulating the contingency table of the two variables}
\NormalTok{mar_conting=}\KeywordTok{table}\NormalTok{(credit}\OperatorTok{$}\NormalTok{MARRIAGE, credit}\OperatorTok{$}\NormalTok{DEFAULT_PAYMENT_NEXT_MONTH)}
\NormalTok{mar_conting }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          
##               0     1
##   married 10453  3206
##   others    239    84
##   single  12623  3341
##   unknown    49     5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{balloonplot}\NormalTok{(}\KeywordTok{t}\NormalTok{(mar_conting), }\DataTypeTok{main=}\StringTok{'Marital status frequency by default payment status'}\NormalTok{, }\DataTypeTok{xlab=}\StringTok{'Default payment status'}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{'Marital status'}\NormalTok{, }\DataTypeTok{label=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{show.margins=}\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-11-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#This gives the counts of each category in each 'axis' specified}

\CommentTok{#Chi-squared test}
\NormalTok{chi_sq_test<-}\KeywordTok{chisq.test}\NormalTok{(mar_conting)}
\NormalTok{chi_sq_test}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's Chi-squared test
## 
## data:  mar_conting
## X-squared = 35.662, df = 3, p-value = 8.826e-08
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#round(chi_sq_test$expected,2)}

\CommentTok{#To determine the nature of the dependence between rows (education) and columns (payment status), use chi-sq residuals (Pearson residuals)}
\NormalTok{chisq_resid<-}\KeywordTok{round}\NormalTok{(chi_sq_test}\OperatorTok{$}\NormalTok{residuals,}\DecValTok{3}\NormalTok{)}
\NormalTok{chisq_resid}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          
##                0      1
##   married -1.790  3.359
##   others  -0.791  1.485
##   single   1.706 -3.201
##   unknown  1.071 -2.009
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Visualization of the residuals shows the positive (blue) and negative (red) correlations between the row and column variables.}
\KeywordTok{corrplot}\NormalTok{(chisq_resid, }\DataTypeTok{is.cor=}\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-11-2.pdf}
Is default status determined by sex?

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Performing pearson Chi-sq test of independence.}
\CommentTok{#Null hypothesis: "sex is independent of whether or not someone will default, at the 0.05 significance level."}

\CommentTok{#First tabulating the contingency table of the two variables}
\NormalTok{sex_conting=}\KeywordTok{table}\NormalTok{(credit}\OperatorTok{$}\NormalTok{SEX, credit}\OperatorTok{$}\NormalTok{DEFAULT_PAYMENT_NEXT_MONTH)}
\NormalTok{sex_conting }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         
##              0     1
##   female 14349  3763
##   male    9015  2873
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{balloonplot}\NormalTok{(}\KeywordTok{t}\NormalTok{(sex_conting), }\DataTypeTok{main=}\StringTok{'Marital status frequency by default payment status'}\NormalTok{, }\DataTypeTok{xlab=}\StringTok{'Default payment status'}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{'Sex'}\NormalTok{, }\DataTypeTok{label=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{show.margins=}\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-12-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#This gives the counts of each category in each 'axis' specified}

\CommentTok{#Chi-squared test}
\NormalTok{chi_sq_test<-}\KeywordTok{chisq.test}\NormalTok{(sex_conting)}
\NormalTok{chi_sq_test}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's Chi-squared test with Yates' continuity correction
## 
## data:  sex_conting
## X-squared = 47.709, df = 1, p-value = 4.945e-12
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#round(chi_sq_test$expected,2)}

\CommentTok{#To determine the nature of the dependence between rows (education) and columns (payment status), use chi-sq residuals (Pearson residuals)}
\NormalTok{chisq_resid<-}\KeywordTok{round}\NormalTok{(chi_sq_test}\OperatorTok{$}\NormalTok{residuals,}\DecValTok{3}\NormalTok{)}
\NormalTok{chisq_resid}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         
##               0      1
##   female  2.049 -3.845
##   male   -2.529  4.746
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Visualization of the residuals shows the positive (blue) and negative (red) correlations between the row and column variables.}
\KeywordTok{corrplot}\NormalTok{(chisq_resid, }\DataTypeTok{is.cor=}\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-12-2.pdf}

Visualization of bill amount due vs.~payment status

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(credit}\OperatorTok{$}\NormalTok{PAY_}\DecValTok{1}\NormalTok{, credit}\OperatorTok{$}\NormalTok{BILL_AMT1, }\DataTypeTok{main=}\StringTok{'Payment status or deferral by bill amount'}\NormalTok{, }\DataTypeTok{xlab=}\StringTok{'Payment status code'}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{'Bill amount (NT dollar)'}\NormalTok{, }\DataTypeTok{col=}\StringTok{'darkgreen'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-13-1.pdf}
Visualization of bill amount due vs.~amount paid

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#par(mfrow=c(3,2))}
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{credit)}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{mapping=}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{credit}\OperatorTok{$}\NormalTok{PAY_AMT1, }\DataTypeTok{y=}\NormalTok{credit}\OperatorTok{$}\NormalTok{BILL_AMT1))}\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{'Amount paid vs. Amount Due, Bill 1'}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Bill amount, NT dollars"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Amount paid, NT dollars"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-14-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{credit)}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{mapping=}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{credit}\OperatorTok{$}\NormalTok{PAY_AMT2, }\DataTypeTok{y=}\NormalTok{credit}\OperatorTok{$}\NormalTok{BILL_AMT2))}\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{'Amount paid vs. Amount Due, Bill 2'}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Bill amount, NT dollars"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Amount paid, NT dollars"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-14-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{credit)}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{mapping=}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{credit}\OperatorTok{$}\NormalTok{PAY_AMT3, }\DataTypeTok{y=}\NormalTok{credit}\OperatorTok{$}\NormalTok{BILL_AMT3))}\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{'Amount paid vs. Amount Due, Bill 3'}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Bill amount, NT dollars"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Amount paid, NT dollars"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-14-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{credit)}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{mapping=}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{credit}\OperatorTok{$}\NormalTok{PAY_AMT4, }\DataTypeTok{y=}\NormalTok{credit}\OperatorTok{$}\NormalTok{BILL_AMT4))}\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{'Amount paid vs. Amount Due, Bill 4'}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Bill amount, NT dollars"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Amount paid, NT dollars"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-14-4.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{credit)}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{mapping=}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{credit}\OperatorTok{$}\NormalTok{PAY_AMT5, }\DataTypeTok{y=}\NormalTok{credit}\OperatorTok{$}\NormalTok{BILL_AMT5))}\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{'Amount paid vs. Amount Due, Bill 5'}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Bill amount, NT dollars"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Amount paid, NT dollars"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-14-5.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{credit)}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{mapping=}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{credit}\OperatorTok{$}\NormalTok{PAY_AMT6, }\DataTypeTok{y=}\NormalTok{credit}\OperatorTok{$}\NormalTok{BILL_AMT6))}\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{'Amount paid vs. Amount Due, Bill 6'}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Bill amount, NT dollars"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Amount paid, NT dollars"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-14-6.pdf}
Now all on one plot

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#all on one plot}
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{credit)}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{mapping=}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{credit}\OperatorTok{$}\NormalTok{PAY_AMT1, }\DataTypeTok{y=}\NormalTok{credit}\OperatorTok{$}\NormalTok{BILL_AMT1, }\DataTypeTok{col=}\StringTok{'Bill 1'}\NormalTok{))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{mapping=}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{credit}\OperatorTok{$}\NormalTok{PAY_AMT2, }\DataTypeTok{y=}\NormalTok{credit}\OperatorTok{$}\NormalTok{BILL_AMT2, }\DataTypeTok{col=}\StringTok{'Bill 2'}\NormalTok{))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{mapping=}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{credit}\OperatorTok{$}\NormalTok{PAY_AMT3, }\DataTypeTok{y=}\NormalTok{credit}\OperatorTok{$}\NormalTok{BILL_AMT3, }\DataTypeTok{col=}\StringTok{'Bill 3'}\NormalTok{))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{mapping=}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{credit}\OperatorTok{$}\NormalTok{PAY_AMT4, }\DataTypeTok{y=}\NormalTok{credit}\OperatorTok{$}\NormalTok{BILL_AMT4, }\DataTypeTok{col=}\StringTok{'Bill 4'}\NormalTok{))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{mapping=}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{credit}\OperatorTok{$}\NormalTok{PAY_AMT5, }\DataTypeTok{y=}\NormalTok{credit}\OperatorTok{$}\NormalTok{BILL_AMT5, }\DataTypeTok{col=}\StringTok{'Bill 5'}\NormalTok{))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{mapping=}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{credit}\OperatorTok{$}\NormalTok{PAY_AMT6, }\DataTypeTok{y=}\NormalTok{credit}\OperatorTok{$}\NormalTok{BILL_AMT6, }\DataTypeTok{col=}\StringTok{'Bill 6'}\NormalTok{))}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{'Amount paid, NT dollars'}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{'Bill amount, NT dollars'}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{'Amount paid vs. Amount due, All Bills'}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{color=}\StringTok{'Bill Number'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-15-1.pdf}
Is this relationship linear?

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow=}\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\NormalTok{linreg <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(PAY_AMT1}\OperatorTok{~}\NormalTok{BILL_AMT1, }\DataTypeTok{data=}\NormalTok{credit)}
\KeywordTok{plot}\NormalTok{(linreg)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-16-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#No, the relationship is nonlinear. It appears to follow an inverse exponential curve.}
\end{Highlighting}
\end{Shaded}

Is there a pattern in bill repayment over time? It seems as though
people tend to start out paying less of the bill at once, then later on
in the billing cycle, they start to pay more than their current bill -
to make up for last time?

What about analysis of the total amount due during the 6 months prior,
and total amount paid? Who is still in-debt by the time bill 7 rolls
around?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{credit_totals<-credit }\OperatorTok{%>%}\StringTok{ }\KeywordTok{group_by}\NormalTok{(ID)}\OperatorTok{%>%}\StringTok{ }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{totaldue=}\KeywordTok{sum}\NormalTok{(BILL_AMT1, BILL_AMT2, BILL_AMT3, BILL_AMT4, BILL_AMT5, BILL_AMT6), }\DataTypeTok{totalpaid=}\KeywordTok{sum}\NormalTok{(PAY_AMT1, PAY_AMT2, PAY_AMT3, PAY_AMT4, PAY_AMT5, PAY_AMT6), }\DataTypeTok{totaldebt=}\NormalTok{totaldue}\OperatorTok{-}\NormalTok{totalpaid)}
\KeywordTok{head}\NormalTok{(credit_totals)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 28
## # Groups:   ID [6]
##      ID LIMIT_BAL SEX   EDUCATION MARRIAGE   AGE PAY_1 PAY_2 PAY_3 PAY_4
##   <int>     <int> <fct> <fct>     <fct>    <int> <int> <int> <int> <int>
## 1     1     20000 fema~ under gr~ married     24     2     2    -1    -1
## 2     2    120000 fema~ under gr~ single      26    -1     2     0     0
## 3     3     90000 fema~ under gr~ single      34     0     0     0     0
## 4     4     50000 fema~ under gr~ married     37     0     0     0     0
## 5     5     50000 male  under gr~ married     57    -1     0    -1     0
## 6     6     50000 male  graduate  single      37     0     0     0     0
## # ... with 18 more variables: PAY_5 <int>, PAY_6 <int>, BILL_AMT1 <int>,
## #   BILL_AMT2 <int>, BILL_AMT3 <int>, BILL_AMT4 <int>, BILL_AMT5 <int>,
## #   BILL_AMT6 <int>, PAY_AMT1 <int>, PAY_AMT2 <int>, PAY_AMT3 <int>,
## #   PAY_AMT4 <int>, PAY_AMT5 <int>, PAY_AMT6 <int>,
## #   DEFAULT_PAYMENT_NEXT_MONTH <fct>, totaldue <int>, totalpaid <int>,
## #   totaldebt <int>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#This new dataframe shows the total due, total paid, and total debt amount at the end of the 6 month period, per person. }
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(credit_totals)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        ID          LIMIT_BAL           SEX                 EDUCATION    
##  Min.   :    1   Min.   :  10000   female:18112   graduate      :10585  
##  1st Qu.: 7501   1st Qu.:  50000   male  :11888   high school   : 4917  
##  Median :15000   Median : 140000                  others        :  123  
##  Mean   :15000   Mean   : 167484                  under graduate:14030  
##  3rd Qu.:22500   3rd Qu.: 240000                  uneducated    :   14  
##  Max.   :30000   Max.   :1000000                  unknown       :  331  
##     MARRIAGE          AGE            PAY_1             PAY_2        
##  married:13659   Min.   :21.00   Min.   :-2.0000   Min.   :-2.0000  
##  others :  323   1st Qu.:28.00   1st Qu.:-1.0000   1st Qu.:-1.0000  
##  single :15964   Median :34.00   Median : 0.0000   Median : 0.0000  
##  unknown:   54   Mean   :35.49   Mean   :-0.0167   Mean   :-0.1338  
##                  3rd Qu.:41.00   3rd Qu.: 0.0000   3rd Qu.: 0.0000  
##                  Max.   :79.00   Max.   : 8.0000   Max.   : 8.0000  
##      PAY_3             PAY_4             PAY_5             PAY_6        
##  Min.   :-2.0000   Min.   :-2.0000   Min.   :-2.0000   Min.   :-2.0000  
##  1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000  
##  Median : 0.0000   Median : 0.0000   Median : 0.0000   Median : 0.0000  
##  Mean   :-0.1662   Mean   :-0.2207   Mean   :-0.2662   Mean   :-0.2911  
##  3rd Qu.: 0.0000   3rd Qu.: 0.0000   3rd Qu.: 0.0000   3rd Qu.: 0.0000  
##  Max.   : 8.0000   Max.   : 8.0000   Max.   : 8.0000   Max.   : 8.0000  
##    BILL_AMT1         BILL_AMT2        BILL_AMT3         BILL_AMT4      
##  Min.   :-165580   Min.   :-69777   Min.   :-157264   Min.   :-170000  
##  1st Qu.:   3559   1st Qu.:  2985   1st Qu.:   2666   1st Qu.:   2327  
##  Median :  22382   Median : 21200   Median :  20089   Median :  19052  
##  Mean   :  51223   Mean   : 49179   Mean   :  47013   Mean   :  43263  
##  3rd Qu.:  67091   3rd Qu.: 64006   3rd Qu.:  60165   3rd Qu.:  54506  
##  Max.   : 964511   Max.   :983931   Max.   :1664089   Max.   : 891586  
##    BILL_AMT5        BILL_AMT6          PAY_AMT1         PAY_AMT2      
##  Min.   :-81334   Min.   :-339603   Min.   :     0   Min.   :      0  
##  1st Qu.:  1763   1st Qu.:   1256   1st Qu.:  1000   1st Qu.:    833  
##  Median : 18105   Median :  17071   Median :  2100   Median :   2009  
##  Mean   : 40311   Mean   :  38872   Mean   :  5664   Mean   :   5921  
##  3rd Qu.: 50191   3rd Qu.:  49198   3rd Qu.:  5006   3rd Qu.:   5000  
##  Max.   :927171   Max.   : 961664   Max.   :873552   Max.   :1684259  
##     PAY_AMT3         PAY_AMT4         PAY_AMT5           PAY_AMT6       
##  Min.   :     0   Min.   :     0   Min.   :     0.0   Min.   :     0.0  
##  1st Qu.:   390   1st Qu.:   296   1st Qu.:   252.5   1st Qu.:   117.8  
##  Median :  1800   Median :  1500   Median :  1500.0   Median :  1500.0  
##  Mean   :  5226   Mean   :  4826   Mean   :  4799.4   Mean   :  5215.5  
##  3rd Qu.:  4505   3rd Qu.:  4013   3rd Qu.:  4031.5   3rd Qu.:  4000.0  
##  Max.   :896040   Max.   :621000   Max.   :426529.0   Max.   :528666.0  
##  DEFAULT_PAYMENT_NEXT_MONTH    totaldue         totalpaid      
##  0:23364                    Min.   :-336259   Min.   :      0  
##  1: 6636                    1st Qu.:  28688   1st Qu.:   6680  
##                             Median : 126311   Median :  14383  
##                             Mean   : 269862   Mean   :  31651  
##                             3rd Qu.: 342626   3rd Qu.:  33504  
##                             Max.   :5263883   Max.   :3764066  
##    totaldebt       
##  Min.   :-2671514  
##  1st Qu.:    4521  
##  Median :  101923  
##  Mean   :  238210  
##  3rd Qu.:  305718  
##  Max.   : 4116080
\end{verbatim}

The summary tables show that the mean `total debt' is \$238,210, with a
minimum of a negative amount meaning an overpayment (of \$2,671,514) and
a maximum debt of \$4,116,080. - note these are NT
dollars\ldots{}convert.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Visualize total debt.}
\NormalTok{credit_totals}\OperatorTok{$}\NormalTok{DEFAULT_PAYMENT_NEXT_MONTH<-}\KeywordTok{as.factor}\NormalTok{(credit_totals}\OperatorTok{$}\NormalTok{DEFAULT_PAYMENT_NEXT_MONTH)}

\CommentTok{#barchart(credit_totals$totaldue, credit_totals$totalpaid, credit_totals$totaldebt)}
\CommentTok{#Note - this is not how I want to visualize this...having trouble thinking of a better way}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{credit_totals)}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{mapping=}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{totalpaid, }\DataTypeTok{y=}\NormalTok{totaldue, }\DataTypeTok{col=}\NormalTok{DEFAULT_PAYMENT_NEXT_MONTH))}\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"6-month total payments vs. total dues"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Total bill amount due (sum of 6 months, NT dollar)"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Total amount paid over 6 months, NT dollar"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{color=}\StringTok{'Default payment }\CharTok{\textbackslash{}n}\StringTok{status'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-20-1.pdf}
log-log regression negative values - will break the model\ldots{}

Can we cluster the above graph into two types of people - those who are
in debt vs.~those who are not?

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#K-means clustering}

\CommentTok{#first subset only the numeric columns of the data.}
\NormalTok{numeric<-}\KeywordTok{cbind}\NormalTok{(}\KeywordTok{unlist}\NormalTok{(}\KeywordTok{lapply}\NormalTok{(credit, is.numeric)))}
\NormalTok{numeric<-credit[,numeric]}
\CommentTok{#head(numeric)}

\CommentTok{#Generate the elbow plot to determine best number of clusters}
\NormalTok{model <-}\StringTok{ }\KeywordTok{kmeans}\NormalTok{(}\DataTypeTok{x=}\NormalTok{numeric, }\DataTypeTok{centers=}\DecValTok{2}\NormalTok{)}
\NormalTok{model}\OperatorTok{$}\NormalTok{tot.withinss}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 8.271888e+14
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tot_withinss<-}\StringTok{ }\KeywordTok{map_dbl}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{20}\NormalTok{, }\ControlFlowTok{function}\NormalTok{(k)\{}
\NormalTok{  model <-}\StringTok{ }\KeywordTok{kmeans}\NormalTok{(}\DataTypeTok{x=}\NormalTok{numeric, }\DataTypeTok{centers=}\NormalTok{k)}
\NormalTok{  model}\OperatorTok{$}\NormalTok{tot.withinss}
\NormalTok{\})}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: did not converge in 10 iterations

## Warning: did not converge in 10 iterations
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{elbow_df <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}
  \DataTypeTok{k=}\DecValTok{1}\OperatorTok{:}\DecValTok{20}\NormalTok{,}
  \DataTypeTok{tot_withinss=}\NormalTok{tot_withinss}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

now plot the elbow plot

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(elbow_df, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{k, }\DataTypeTok{y=}\NormalTok{tot_withinss))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_line}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_x_continuous}\NormalTok{(}\DataTypeTok{breaks=}\DecValTok{1}\OperatorTok{:}\DecValTok{200}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{xlim}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{15}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Elbow plot to determine optimim k value"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Number of clusters, k"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Total within-cluster-sum-of-squares"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Scale for 'x' is already present. Adding another scale for 'x', which
## will replace the existing scale.
\end{verbatim}

\begin{verbatim}
## Warning: Removed 5 rows containing missing values (geom_point).
\end{verbatim}

\begin{verbatim}
## Warning: Removed 5 rows containing missing values (geom_path).
\end{verbatim}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-22-1.pdf}
Based on this plot it looks like 4 clusters is probably ideal. Run the
k-means clustering with 4 clusters:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Running the cluster analysis with 3 clusters.}
\NormalTok{km <-}\StringTok{ }\KeywordTok{kmeans}\NormalTok{(numeric, }\DataTypeTok{centers=}\DecValTok{3}\NormalTok{, }\DataTypeTok{iter.max=}\DecValTok{50}\NormalTok{)}

\CommentTok{#Visualizing the clusters.}
\KeywordTok{fviz_cluster}\NormalTok{(km, numeric, }\DataTypeTok{geom=}\KeywordTok{c}\NormalTok{(}\StringTok{"point"}\NormalTok{), }\DataTypeTok{show.clust.cent =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-23-1.pdf}
This shows the clusters outlined as the kmeans algorithm identified
them. The 2 principal components explain 31.1\% and 19.4\% of the
variation in the data respectively.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#PCA analysis of these clusters.}
\NormalTok{pc<-}\KeywordTok{princomp}\NormalTok{(numeric, }\DataTypeTok{cor=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{scores=}\OtherTok{TRUE}\NormalTok{)}
\KeywordTok{summary}\NormalTok{(pc)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Importance of components:
##                           Comp.1    Comp.2    Comp.3     Comp.4     Comp.5
## Standard deviation     2.5570552 2.0159132 1.2283244 1.00817651 0.99643876
## Proportion of Variance 0.3113586 0.1935193 0.0718467 0.04840095 0.04728049
## Cumulative Proportion  0.3113586 0.5048780 0.5767247 0.62512563 0.67240611
##                            Comp.6     Comp.7     Comp.8     Comp.9
## Standard deviation     0.95847007 0.94221875 0.93473357 0.88382331
## Proportion of Variance 0.04374595 0.04227506 0.04160604 0.03719732
## Cumulative Proportion  0.71615206 0.75842711 0.80003315 0.83723047
##                           Comp.10    Comp.11    Comp.12    Comp.13
## Standard deviation     0.85598926 0.83693519 0.76905870 0.63542423
## Proportion of Variance 0.03489131 0.03335526 0.02816435 0.01922686
## Cumulative Proportion  0.87212179 0.90547705 0.93364139 0.95286825
##                           Comp.14   Comp.15     Comp.16     Comp.17
## Standard deviation     0.50981797 0.5004457 0.434329936 0.362751790
## Proportion of Variance 0.01237687 0.0119260 0.008982976 0.006266136
## Cumulative Proportion  0.96524512 0.9771711 0.986154098 0.992420234
##                            Comp.18     Comp.19    Comp.20     Comp.21
## Standard deviation     0.264525447 0.201907515 0.15879467 0.152377764
## Proportion of Variance 0.003332082 0.001941269 0.00120075 0.001105666
## Cumulative Proportion  0.995752316 0.997693584 0.99889433 1.000000000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(pc, }\DataTypeTok{type=}\StringTok{'lines'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-24-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{biplot}\NormalTok{(pc)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-24-2.pdf}
From these plots of the PCA analysis, it looks like there are 3 major
components which are making up the majority of the variation in the
data. It does appear that all the BILL\_AMTs and PAY\_\#'s (payment
statuses) are correlated heavily with each other.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#plot3d(pc$scores[,1:3], col=as.integer(credit$DEFAULT_PAYMENT_NEXT_MONTH))}
\CommentTok{#the above works and makes an awesome graph, but a little hard to interpret since they are components.}

\KeywordTok{plot3d}\NormalTok{(credit}\OperatorTok{$}\NormalTok{PAY_}\DecValTok{1}\NormalTok{, credit}\OperatorTok{$}\NormalTok{BILL_AMT1, credit}\OperatorTok{$}\NormalTok{PAY_AMT1, }\DataTypeTok{col=}\KeywordTok{as.integer}\NormalTok{(credit}\OperatorTok{$}\NormalTok{DEFAULT_PAYMENT_NEXT_MONTH), }\DataTypeTok{xlab=}\StringTok{'Payment status'}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{'Bill amount'}\NormalTok{, }\DataTypeTok{zlab=}\StringTok{'Payment amount'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

other visualizations of the cluster

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Visualizing the clusters.}
\KeywordTok{fviz_pca_ind}\NormalTok{(pc, }\DataTypeTok{geom=}\StringTok{'point'}\NormalTok{, }\DataTypeTok{col.ind=}\NormalTok{credit}\OperatorTok{$}\NormalTok{DEFAULT_PAYMENT_NEXT_MONTH)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-26-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#visualize the variables.}
\KeywordTok{fviz_pca_var}\NormalTok{(pc)}
\end{Highlighting}
\end{Shaded}

\includegraphics{SQL-NoSQL_Visualizations_files/figure-latex/unnamed-chunk-27-1.pdf}
We can see the three major variables contributing to the clustering
based on the above variable graph: generally, `payment status', `bill
amount', and `payment amount'.


\end{document}
